### ISSUE TITLE
OpenAPI3 spec: parameter type property is no longer valid

### ISSUE THREAD

**Issue by MikeRalphson** [metadevpro/baucis-openapi3#2]
Can't believe I didn't spot this until now, but the `parameter.type` property (and associated properties such as `format`, `default` etc) has been removed completely from the OpenAPI3 spec.

To constrain a parameter to a type you now need to declare a `schema` property.

My converter/validator has been updated, as of ~~v1.2.0~~ v1.2.1 (also affected headers.type)

**Comment by pjmolina** [comment]
Good catch. Same here, didn't notice and was a big one. Fixing asap.
Thanks for reporting.
