### ISSUE TITLE
Filter out disabled HTTP methods

### ISSUE THREAD

**Issue by swordfish444** [metadevpro/baucis-openapi3#31]
## Description

In Baucis, you can disable HTTP methods per controller. Disabled methods are still being written to the openapi response. 

## Proposed solutions

Filter out disabled methods when constructing the openapi response.

## References

![image](https://user-images.githubusercontent.com/3893966/55345441-b7e1c480-5464-11e9-9eae-fbe60f9b71e5.png)

![image](https://user-images.githubusercontent.com/3893966/55345473-c7f9a400-5464-11e9-84e0-ede509abf24d.png)

-----

@pjmolina Is there a reason this is not the default behavior in baucis-operapi3?

**Comment by pjmolina** [comment]
Merged and published as npm version `0.3.0`.
Just changed your code a little to preserve the order of emitted operations: instance first, collections later.
Thank you @swordfish444 !
